#-*- coding: utf-8 -*-
[HTTP]
scheme = http
testurl = 测试环境
testport = 9024

uaturl = uat环境
uatport = 9224
timeout = 10.0


[EMAIL]
on_off = open
mail_server = smtp.qq.com
subject = 接口自动化测试报告
app = Outlook
send_addr = 发送人邮箱
reciver_addr = 收件人邮箱
#发件人邮箱授权码
mail_pwd =


[MYSQL]
host =
user = test
passwd = 19960904

testhost =
testuser = test-admin
testpasswd = test123456

port = 3306
db =
charset = utf8