platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
name: huihui
age: 18
- '123'
- 23
- 2132
- - '123'
  - 23
  - 2132

